export type MediaControllerKey = keyof typeof MEDIA_CONTROLLER_KEYS;

/**
 * Maps "event.key" values from a KeyboardEvent to a set of keys specifically related to media controller functionalities.
 * This constant object facilitates handling keyboard interactions for various media controller actions like changing inputs,
 * toggling subtitles, navigating through media guides, and managing playback settings. The mapping ensures uniform handling
 * of these keys across different systems and remains consistent even when the "Shift" key is pressed.
 *
 * @example
 * let command = 'ZoomToggle'; // This could be from an event.key
 * let action = MEDIA_CONTROLLER_KEYS[command];
 * console.log(action); // Output will be 'ZoomToggle'
 *
 * @type {{ [key in string]: string }}
 */
export const MEDIA_CONTROLLER_KEYS = {
  AVRInput: 'AVRInput',
  AVRPower: 'AVRPower',
  ColorF0Red: 'ColorF0Red',
  ColorF1Green: 'ColorF1Green',
  ColorF2Yellow: 'ColorF2Yellow',
  ColorF3Blue: 'ColorF3Blue',
  ColorF4Grey: 'ColorF4Grey',
  ColorF5Brown: 'ColorF5Brown',
  ClosedCaptionToggle: 'ClosedCaptionToggle',
  Dimmer: 'Dimmer',
  DisplaySwap: 'DisplaySwap',
  DVR: 'DVR',
  Exit: 'Exit',
  FavoriteClear0: 'FavoriteClear0',
  FavoriteClear1: 'FavoriteClear1',
  FavoriteClear2: 'FavoriteClear2',
  FavoriteClear3: 'FavoriteClear3',
  FavoriteRecall0: 'FavoriteRecall0',
  FavoriteRecall1: 'FavoriteRecall1',
  FavoriteRecall2: 'FavoriteRecall2',
  FavoriteRecall3: 'FavoriteRecall3',
  FavoriteStore0: 'FavoriteStore0',
  FavoriteStore1: 'FavoriteStore1',
  FavoriteStore2: 'FavoriteStore2',
  FavoriteStore3: 'FavoriteStore3',
  Guide: 'Guide',
  GuideNextDay: 'GuideNextDay',
  GuidePreviousDay: 'GuidePreviousDay',
  Info: 'Info',
  InstantReplay: 'InstantReplay',
  Link: 'Link',
  ListProgram: 'ListProgram',
  LiveContent: 'LiveContent',
  Lock: 'Lock',
  MediaApps: 'MediaApps',
  MediaAudioTrack: 'MediaAudioTrack',
  MediaLast: 'MediaLast',
  MediaSkipBackward: 'MediaSkipBackward',
  MediaSkipForward: 'MediaSkipForward',
  MediaStepBackward: 'MediaStepBackward',
  MediaStepForward: 'MediaStepForward',
  MediaTopMenu: 'MediaTopMenu',
  NavigateIn: 'NavigateIn',
  NavigateNext: 'NavigateNext',
  NavigateOut: 'NavigateOut',
  NavigatePrevious: 'NavigatePrevious',
  NextFavoriteChannel: 'NextFavoriteChannel',
  NextUserProfile: 'NextUserProfile',
  OnDemand: 'OnDemand',
  Pairing: 'Pairing',
  PinPDown: 'PinPDown',
  PinPMove: 'PinPMove',
  PinPToggle: 'PinPToggle',
  PinPUp: 'PinPUp',
  PlaySpeedDown: 'PlaySpeedDown',
  PlaySpeedReset: 'PlaySpeedReset',
  PlaySpeedUp: 'PlaySpeedUp',
  RandomToggle: 'RandomToggle',
  RcLowBattery: 'RcLowBattery',
  RecordSpeedNext: 'RecordSpeedNext',
  RfBypass: 'RfBypass',
  ScanChannelsToggle: 'ScanChannelsToggle',
  ScreenModeNext: 'ScreenModeNext',
  Settings: 'Settings',
  SplitScreenToggle: 'SplitScreenToggle',
  STBInput: 'STBInput',
  STBPower: 'STBPower',
  Subtitle: 'Subtitle',
  Teletext: 'Teletext',
  VideoModeNext: 'VideoModeNext',
  Wink: 'Wink',
  ZoomToggle: 'ZoomToggle',
};
